### ISSUE TITLE
Shortcut not recognised in neovim

### ISSUE THREAD

**Issue by sam-sjs** [knubie/vim-kitty-navigator#16]
Hey @knubie, thanks heaps for putting this plugin together, appreciate your work.

My issue seems to be the same as what was reported in #2 and #8 where <C-h/j/k/l> work fine for navigating in the terminal but when inside Neovim it skips over any splits and goes directly into the closest terminal window.  It also will not enter a vim window from a terminal window.

When I load nvim into iterm2 navigation is as expected and <C-h/j/k/l> navigates nvim spits correctly so i imagine this has something to do with the command being intercepted by kitty and not passed correctly to nvim but I don't understand the python scripts well enough to look into it.

Fairly sure this was working when I set it all up last night and then had stopped this morning but I may have just been tired.  I don't believe anything has changed since then, there are no other plugins running besides vim-plug.  Have tried a full reinstall of nvim/kitty/vim-plug/vim-kitty-navigatior to be sure but still no dice.

kitty version: 0.21.2
nvim version: 0.5.0

**Comment by knubie** [comment]
Hi @sam-sjs , thank you for the kind words. 😊

As for not being able to navigate within in, this is usually because the script is not able to detect that you're inside of vim. The script will examine the foreground process to see if it matches `n?vim`, and if so, it will "do nothing" and just let neovim interpret the shortcut (ie. navigate between vim splits). If it does match, then it will intercept the shortcut and move kitty splits. https://github.com/knubie/vim-kitty-navigator/blob/master/pass_keys.py#L42-L47

You can also supply a fourth argument to `pass_keys.py` which is a regex that the script will use to match against the window title instead of checking the current foreground process. https://github.com/knubie/vim-kitty-navigator/blob/master/pass_keys.py#L38-L41

You can try going down the title route just to see if it works. (ie. Setting vim's title manually in your `.vimrc` and adding that optional regex argument to `pass_keys.py`.) That option is documented in the `README.md`.

The fact that it doesn't go from a non-vim kitty window to a vim kitty window is really odd. I can't think of what would cause that.

**Comment by sam-sjs** [comment]
Cheers for getting back so quick mate.

I've been playing with this over the day, removed every terminal emulator nuked .zshrc, reinstalled kitty/nvim/vim-plug/vim-kitty-navigator and am running with just that at the moment.

With both the title method and the regular method I can now:
  - Navigate around Neovim
  - Navigate around Kitty windows
  - Navigate from Kitty window to Neovim window

What I can't do:
  - Navigate from Neovim window to Kitty window

I'll keep fiddling and post back if I figure out what's causing the issue.

**Comment by sam-sjs** [comment]
Ok on further investigation it looks like my issue is on line 49 of `pass_keys.py`

```
Press: native_key: 0x26 (j) glfw_key: 0x6a mods: ctrl char_count: 1 deadKeyState: 0 repeat: 0 text: <none> glfw_key: j marked_text: 
on_key_input: glfw key: 0x6a native_code: 0x26 action: PRESS mods: ctrl text: '' state: 0 updateIMEState: 3.000000, 2.000000, 7.000000, 13.000000
KeyPress matched action: kitten
Traceback (most recent call last):
  File "lib/python3.9/kitty/boss.py", line 694, in dispatch_possible_special_key
  File "lib/python3.9/kitty/boss.py", line 765, in dispatch_action
  File "lib/python3.9/kitty/boss.py", line 1013, in kitten
  File "lib/python3.9/kitty/boss.py", line 954, in _run_kitten
  File "/Users/sam/.config/kitty/pass_keys.py", line 49, in handle_result
    mods, key, is_text = ku.parse_kittens_shortcut(args[3])
AttributeError: module 'kitty.conf.utils' has no attribute 'parse_kittens_shortcut'
sent key to child
Release: native_key: 0x26 (j) glfw_key: 0x6a mods: ctrl
```

After looking into `kitty.conf.utils` it doesn't look like there is a `parse_kittens_shortcut`

Have I missed something?

**Comment by knubie** [comment]
Thanks for the sleuthing @sam-sjs ! I appreciate the help in maintaining this plugin. It looks like we should be able to replace `parse_kittens_shortcut` with `parse_kittens_key`, and just re-arrange the arguments. I'd be happy to accept a PR if you are up for it. I found this old thread as well: https://github.com/kovidgoyal/kitty/issues/1465 so it might be worth pinging the author if you get stuck.
